package main

import (
	"fmt"
	"strconv"
)

func main() {
	b := []byte("rune (ascii):")

	// AppendQuoteRuneToASCII appends a single-quoted Go character
	// literal representing the rune, as generated by QuoteRuneToASCII,
	// to dst and returns the extended buffer.
	b = strconv.AppendQuoteRuneToASCII(b, '☺')

	fmt.Println(string(b))
}
