package main

import (
	"fmt"
	"strconv"
)

func main() {
	b10 := []byte("int (base 10):")

	// Append the integer 15 as base 10 to b10
	//
	// AppendInt appends the string form of the integer i,
	// as generated by FormatInt, to dst and returns the extended buffer.
	b10 = strconv.AppendInt(b10, 15, 10)
	fmt.Println(string(b10)) // 15

	b16 := []byte("int (base 16):")

	// Append the integer 15 as base 16 to b16
	b16 = strconv.AppendInt(b16, 15, 16)
	fmt.Println(string(b16)) // f
}
